name: Test kodr RLNC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Run all tests
      run: go test -v -cover -count=10 ./...    

    - name: Run Full RLNC example
      run: pushd examples/full; go run main.go; popd

    - name: Run Systematic RLNC example
      run: pushd examples/systematic; go run main.go; popd
